### ISSUE TITLE
JSON output not showing any result

### ISSUE THREAD

**Issue by mtrohman** [krylovsk/mqtt-benchmark#3] opened 2017-09-26 06:47 UTC
JSON not showing result but it publishes mqtt payload.
Txt result work perfectly

compiling from github source

**Comment by krylovsk** [comment] 2018-06-17 12:35
Sorry for a late response, apparently the email notification got lost in my inbox.
I've just tried and couldn't reproduce the issue. Could you provide more details?

**Comment by licensedslacker** [comment] 2019-06-03 12:31
Got the same issue when a number of clients were set to 1. When the number of clients is more than 1, it will work. As the original reported said, the text output works, but no JSON output.

**Comment by krylovsk** [comment] 2019-06-03 12:36
Thanks, let me re-check that and come back.

**Comment by krylovsk** [comment] 2019-10-13 15:29
@mtrohman thanks for reporting and @licensedslacker for re-opening (and sorry for a late follow-up).
The issue is in the lack of NaN support in JSON (https://tools.ietf.org/html/rfc4627#section-2.4). Will fix after #6 is merged.

**Comment by krylovsk** [comment] 2019-10-13 15:45
Fixed and released v0.1.1

**Closed by krylovsk** 2019-10-13 15:45 UTC
