### ISSUE TITLE
No Json when there is only 1 client

### ISSUE THREAD

**Issue by edoardesd** [krylovsk/mqtt-benchmark#7] opened 2019-09-30 12:59 UTC
When `--clients 1` is activated no json is displayed

**Comment by krylovsk** [comment] 2019-10-13 15:27
Thanks, the issue is in the lack of `NaN` support in JSON (https://tools.ietf.org/html/rfc4627#section-2.4)

Will fix after #6 is merged.

**Comment by krylovsk** [comment] 2019-10-13 15:27
(closing as duplicate of #3)

**Closed by krylovsk** 2019-10-13 15:27 UTC
